name: DEFAULT
infra: docker
hyperparameter: 0.5
rate: 10 
duration: 10
addrs:
  - "localhost:9091"
  - "localhost:9092"
  - "localhost:9093"
  - "localhost:9094"
  - "localhost:9095"
  - "localhost:9096"
  - "localhost:9097"
  - "localhost:9098"
steps:
  - action: "CONNECT"
    desc: "Establish connection workers."
    data: 0
  - action: "PARENT"
    desc: "Choose next node for tree."
    data: 0
