infra: gcp
addrs:
- 10.1.1.0:9091
- 10.1.1.1:9091
- 10.1.1.2:9091
- 10.1.1.3:9091
- 10.1.1.4:9091
- 10.1.1.5:9091
- 10.1.1.6:9091
- 10.1.1.7:9091
- 10.1.1.8:9091
params:
  hyperparameter: 4
  rate: 1000
  duration: 30
  fanout: 2
  depth: 2
runs:
- name: BEST
  strategy:
    best: true
- name: WORST
  strategy:
    best: false
- name: RAND
  strategy:
    best: true
