name: DEFAULT
infra: docker
hyperparameter: 0.5
rate: 10 
duration: 2
addrs:
  - "localhost:9091"
  - "localhost:9092"
  - "localhost:9093"
  - "localhost:9094"
  - "localhost:9095"
  - "localhost:9096"
  - "localhost:9097"
  - "localhost:9098"
  - "localhost:9099"
runs:
  - step: "PARENT"
    name: "BEST"
    best: True
  # - step: "PARENT"
  #   name: "WORST"
  #   best: False
  # - step: "RAND"
  #   name: "RANDOM"
  #   best: True
