resources:
- name: base-dev
  properties:
    disks:
    - autoDelete: true
      boot: true
      deviceName: boot
      initializeParams:
        sourceImage: projects/multicast1/global/images/multicast-ubuntu-2204-ebpf
      type: PERSISTENT
    machineType: zones/us-east4-c/machineTypes/e2-standard-4
    metadata:
      items:
      - key: startup-script
        value: ""
      - key: KEY
        value: VALUE
    networkInterfaces:
    - accessConfigs:
      - networkTier: PREMIUM
        type: ONE_TO_ONE_NAT
      network: projects/multicast1/global/networks/multicast-management
      networkIP: 10.1.1.16
      nicType: GVNIC
      stackType: IPV4_ONLY
      subnetwork: projects/multicast1/regions/us-east4/subnetworks/multicast-management
    - network: projects/multicast1/global/networks/multicast-service
      networkIP: 10.0.1.16
      nicType: GVNIC
      stackType: IPV4_ONLY
      subnetwork: projects/multicast1/regions/us-east4/subnetworks/multicast-service
    serviceAccounts:
    - email: multicast-service-vm@multicast1.iam.gserviceaccount.com
      scopes:
      - https://www.googleapis.com/auth/cloud-platform
    zone: us-east4-c
  type: compute.v1.instance
